<?php

/**
 * @file
 * Contains socialfeed.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_help().
 */
function socialfeed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the socialfeed module.
    case 'help.page.socialfeed':
      $output = '';
      $output .= '<h3>' . new TranslatableMarkup('About') . '</h3>';
      $output .= '<p>' . new TranslatableMarkup('The Socialfeed module allows you to fetch feeds directly from Facebook, Twitter & Instagram by simply installing it via <code>composer require drupal/socialfeed</code>') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function socialfeed_theme($existing, $type, $theme, $path) {
  return [
    'socialfeed_facebook_post' => [
      'variables' => ['post' => [], 'permalink_url' => NULL],
      'file' => 'socialfeed.facebook.theme.inc',
      'path' => $path . '/templates/facebook',
    ],
    'socialfeed_twitter_post' => [
      'variables' => ['post' => [], 'tweet' => NULL, 'tweet_url' => NULL],
      'file' => 'socialfeed.twitter.theme.inc',
      'path' => $path . '/templates/twitter',
    ],
    'socialfeed_instagram_post_video' => [
      'variables' => ['post' => []],
      'file' => 'socialfeed.instagram.theme.inc',
      'path' => $path . '/templates/instagram',
    ],
    'socialfeed_instagram_post_image' => [
      'variables' => ['post' => []],
      'file' => 'socialfeed.instagram.theme.inc',
      'path' => $path . '/templates/instagram',
    ],
    'socialfeed_instagram_post_carousel_album' => [
      'variables' => ['post' => []],
      'file' => 'socialfeed.instagram.theme.inc',
      'path' => $path . '/templates/instagram',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function socialfeed_theme_suggestions_socialfeed_facebook_post(array $variables) {
  $type = 'default';
  if (!empty($variables['post']) && is_array($variables['post']) && !empty($variables['post']['status_type'])) {
    $type = $variables['post']['status_type'];
  }
  return [
    'socialfeed_facebook_post__' . $type,
  ];
}
