socialfeed.facebook.settings:
  type: config_object
  label: "Facebook Settings"
  mapping:
    page_id:
      type: string
      label: "Facebook Page ID"
    page_name:
      type: string
      label: "Facebook Page Name"
    app_id:
      type: string
      label: "Facebook App ID"
    secret_key:
      type: string
      label: "Facebook Secret Key"
    user_token:
      type: string
      label: "Facebook User Token"
    page_permanent_token:
      type: string
      label: "Facebook Permanent Token"
    no_feeds:
      type: integer
      label: "Number Of Feeds"
    all_types:
      type: boolean
      label: "Types Of Posts"
    post_type:
      type: string
      label: "Selected Type Of Post To Show"
    display_pic:
      type: boolean
      label: "Show Post Picture"
    display_video:
      type: boolean
      label: "Show Post Video"
    trim_length:
      type: integer
      label: "Trim Length"
    teaser_text:
      type: string
      label: "Teaser Text"
    hashtag:
      type: boolean
      label: "Show Hashtag"
    time_stamp:
      type: boolean
      label: "Show Date/Time"
    time_format:
      type: string
      label: "Date/Time Format"
    use_facebook_style:
      type: boolean
      label: "Use Default Facebook UI Style"

socialfeed.twitter.settings:
  type: config_object
  label: "X (formerly Twitter) Settings"
  mapping:
    consumer_key:
      type: string
      label: "X Consumer Key"
    consumer_secret:
      type: string
      label: "X Consumer Secret"
    access_token:
      type: string
      label: "X Access Token"
    access_token_secret:
      type: string
      label: "X Access Token Secret"
    bearer_token:
      type: string
      label: "X Bearer Token"
    account_id:
      type: string
      label: "X Account ID"
    tweets_count:
      type: integer
      label: "Posts Count"
    hashtag:
      type: boolean
      label: "Show Hashtag"
    time_stamp:
      type: boolean
      label: "Show Date/Time"
    time_format:
      type: string
      label: "Date/Time Format"
    time_ago:
      type: boolean
      label: "Show Date Relative Style"
    trim_length:
      type: integer
      label: "Trim Length"
    teaser_text:
      type: string
      label: "Teaser Text"
    use_twitter_style:
      type: boolean
      label: "Use Default X UI Style"

socialfeed.instagram.settings:
  type: config_object
  label: "Instagram Settings"
  mapping:
    client_id:
      type: string
      label: "Client ID"
    app_secret:
      type: string
      label: "App Secret"
    redirect_uri:
      type: string
      label: "Redirect URI"
    access_token:
      type: string
      label: "Access Token"
    access_token_date:
      type: integer
      label: "Access Token Created Date"
    picture_count:
      type: integer
      label: "Picture Count"
    video_thumbnail:
      type: boolean
      label: "Show Video Thumbnails"
    time_format:
      type: string
      label: "Date/Time Format"
    post_link:
      type: boolean
      label: "Show Post URL"
    use_instagram_style:
      type: boolean
      label: "Use Default Instagram UI Style"
